Possible refactor of _update_attrs_and_maybe_adapt_lights
basnijholt/adaptive-lighting pull request #537
Opened 2023-04-04 06:44 UTC by basnijholt

@th3w1zard1, I am still not sure whether what I did here is better. Give it a look over.

Perhaps it's worse. I will have a fresh look tomorrow!

2023-04-04 08:34 UTC, th3w1zard1 commented on custom_components/adaptive_lighting/switch.py
> +        adapt_brightness = adapt_brightness or self.adapt_brightness_switch.is_on
Yeah I tried this change and ended up with errors in my test. This is your old code pulled from `_adapt_lights`

2023-04-04 08:43 UTC, th3w1zard1 commented
The way I wrote it just seemed cleaner: the logic flowed and made more sense. :shrug.

Looking at this it seems like it'd be difficult to modify if needed later down the line, which was the whole point of the small rewrite

2023-04-04 08:44 UTC, th3w1zard1 requested changes

2023-04-05 16:27 UTC, basnijholt commented on custom_components/adaptive_lighting/switch.py
> +                if manually_controlled:
> What was so bad about the way I wrote this func?


Nothing bad about it! I just personally find it fun to rewrite stuff in order to make the code simpler 😄

2023-04-08 18:11 UTC, th3w1zard1 commented
I've come around to liking this :)

2023-04-08 18:20 UTC, th3w1zard1 approved these changes

2023-04-08 18:22 UTC, merged